version: "3.7"
services:
  web:
    build: 
      context: ../
      dockerfile: docker/web/Dockerfile
    ports:
      - "8081:80"
  farm-army-proxy:
    build: ./farmArmyProxy
    ports:
      - "8082:80"
    