version: "3.7"
services:
  main-proxy:
    build: ./mainProxy
    command: /buildConfig.sh 
    environment:
      WEB_SERVER_NAME: ${WEB_SERVER_NAME}
      WEB_EXTERNAL_PORT: ${WEB_EXTERNAL_PORT}
      WEB_CONTAINER_NAME: ${WEB_CONTAINER_NAME}
      FARM_ARMY_PROXY_SERVER_NAME: ${FARM_ARMY_PROXY_SERVER_NAME}
      FARM_ARMY_PROXY_EXTERNAL_PORT: ${FARM_ARMY_PROXY_EXTERNAL_PORT}
      FARM_ARMY_PROXY_CONTAINER_NAME: ${FARM_ARMY_PROXY_CONTAINER_NAME}
      USE_SSL: ${USE_SSL}
  web:
    build: 
      context: ../
      dockerfile: docker/web/Dockerfile
    container_name: ${WEB_CONTAINER_NAME}
  farm-army-proxy:
    build: ./farmArmyProxy
    container_name: ${FARM_ARMY_PROXY_CONTAINER_NAME}